//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace digitallearningback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer_record
    {
        public int id { get; set; }
        public Nullable<int> lr_id { get; set; }
        public string user_id { get; set; }
        public Nullable<int> q_id { get; set; }
        public Nullable<int> a_id1 { get; set; }
        public Nullable<int> a_id2 { get; set; }
        public Nullable<int> a_id3 { get; set; }
        public Nullable<int> a_id4 { get; set; }
        public Nullable<int> correct_a_id1 { get; set; }
        public Nullable<int> correct_a_id2 { get; set; }
        public Nullable<int> correct_a_id3 { get; set; }
        public Nullable<int> correct_a_id4 { get; set; }
        public Nullable<System.DateTime> joindate { get; set; }
        public Nullable<int> user_login_count { get; set; }
        public Nullable<int> is_correct { get; set; }
        public Nullable<int> ismulti { get; set; }
    }
}
