//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace digitallearningback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer_Group_Log
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Answer_Group_Log()
        {
            this.Answer_Log = new HashSet<Answer_Log>();
        }
    
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> level_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> correct_count { get; set; }
        public Nullable<int> incorrect_count { get; set; }
        public Nullable<System.DateTime> joindate { get; set; }
        public Nullable<int> qsize { get; set; }
    
        public virtual Question_level Question_level { get; set; }
        public virtual Question_group Question_group { get; set; }
        public virtual InfoUser InfoUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer_Log> Answer_Log { get; set; }
    }
}
