//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace digitallearningback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer_Level_Log
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Answer_Level_Log()
        {
            this.Answer_Log = new HashSet<Answer_Log>();
        }
    
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> loginid { get; set; }
        public Nullable<int> gid { get; set; }
        public Nullable<int> lid { get; set; }
        public string qids { get; set; }
        public Nullable<int> isfinished { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<int> correctnumber { get; set; }
        public Nullable<decimal> passpoint { get; set; }
        public string charjson { get; set; }
        public Nullable<int> answernumber { get; set; }
        public Nullable<int> questionnumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer_Log> Answer_Log { get; set; }
        public virtual Question_group Question_group { get; set; }
        public virtual Question_level Question_level { get; set; }
        public virtual LoginLog LoginLog { get; set; }
        public virtual InfoUser InfoUser { get; set; }
    }
}
