//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace digitallearningback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer_Log
    {
        public int id { get; set; }
        public Nullable<int> ag_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> q_id { get; set; }
        public Nullable<int> a_id { get; set; }
        public Nullable<int> correct_a_id { get; set; }
        public Nullable<int> user_login_count { get; set; }
        public Nullable<int> is_correct { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Answer Answer1 { get; set; }
        public virtual Answer_Group_Log Answer_Group_Log { get; set; }
        public virtual Question Question { get; set; }
        public virtual InfoUser InfoUser { get; set; }
    }
}
