//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace digitallearningback.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Character_image
    {
        public int cimage_id { get; set; }
        [DisplayName("圖片")]
        public string cimage_path { get; set; }
        public Nullable<int> cimage_mood { get; set; }
        [DisplayName("性別")]
        public string cimage_gander { get; set; }
        public Nullable<int> cimage_profession { get; set; }
        [DisplayName("新增時間")]
        public Nullable<System.DateTime> cimage_joindate { get; set; }
        public Nullable<int> image_level { get; set; }
    
        public virtual Cimage_mood Cimage_mood1 { get; set; }
        public virtual Cimage_profession Cimage_profession1 { get; set; }
    }
}
