//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace digitallearningback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character_image
    {
        public decimal cimage_id { get; set; }
        public string cimage_path { get; set; }
        public Nullable<decimal> cimage_mood { get; set; }
        public string cimage_gander { get; set; }
        public Nullable<decimal> cimage_profession { get; set; }
        public Nullable<System.DateTime> cimage_joindate { get; set; }
        public Nullable<decimal> image_level { get; set; }
    }
}
