//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace digitallearningback.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class InfoUser
    {
        public int id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string age { get; set; }
        public string grade { get; set; }
        public string character_image { get; set; }
        public string pet_image { get; set; }
        public string pet_name { get; set; }
        [Required]
        public string login_id { get; set; }
        [Required]
        public string password { get; set; }
        public Nullable<System.DateTime> joindate { get; set; }
        public string cimage_type { get; set; }
        public string pimage_type { get; set; }
        public Nullable<decimal> login_count { get; set; }
        public Nullable<decimal> group_id { get; set; }
        public string teacher_id { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<decimal> experience { get; set; }
        public Nullable<decimal> hp { get; set; }
    }
}
