//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace digitallearningback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level_group
    {
        public int lr_id { get; set; }
        public string lr_user_id { get; set; }
        public Nullable<int> lr_group_id { get; set; }
        public Nullable<int> lr_user_login_id { get; set; }
        public Nullable<int> lr_correct_count { get; set; }
        public Nullable<int> lr_incorrect_count { get; set; }
        public Nullable<System.DateTime> lr_joindate { get; set; }
        public Nullable<int> lr_qsize { get; set; }
        public Nullable<int> lr_level_id { get; set; }
    }
}
