//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace digitallearningback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaire_option
    {
        public int id { get; set; }
        public Nullable<int> main_id { get; set; }
        public string text { get; set; }
        public Nullable<int> show_order { get; set; }
    
        public virtual Questionnaire_main Questionnaire_main { get; set; }
    }
}
