//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace digitallearningback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Answer = new HashSet<Answer>();
            this.Question_Concept_Mapping = new HashSet<Question_Concept_Mapping>();
            this.Question_Level_Mapping = new HashSet<Question_Level_Mapping>();
            this.Answer_Log = new HashSet<Answer_Log>();
        }
    
        public int id { get; set; }
        public int groupid { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> joindate { get; set; }
        public string point { get; set; }
        public string tip { get; set; }
        public string pic_path { get; set; }
        public Nullable<int> level_id { get; set; }
        public Nullable<int> ismulti { get; set; }
        public string similar_group { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question_Concept_Mapping> Question_Concept_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question_Level_Mapping> Question_Level_Mapping { get; set; }
        public virtual Question_group Question_group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer_Log> Answer_Log { get; set; }
    }
}
