//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace digitallearningback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DataAnalysisIndexInfo
    {
        public int id { get; set; }
        public Nullable<int> logincount { get; set; }
        public Nullable<int> stdusagcount { get; set; }
        public Nullable<int> stdcount { get; set; }
        public string percentage { get; set; }
        public string level { get; set; }
        public Nullable<int> levelcount { get; set; }
        public Nullable<int> oncelevelcount { get; set; }
        public Nullable<int> multiplelevelcount { get; set; }
        public Nullable<int> multipleTestCompleteCount { get; set; }
        public string oncespercentage { get; set; }
        public string multiplepercentage { get; set; }
    }
}
