//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace digitallearningback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DataAnalysisLevelDetailInfo
    {
        public int id { get; set; }
        public Nullable<int> lid { get; set; }
        public Nullable<int> stop_one { get; set; }
        public Nullable<int> stop_two { get; set; }
        public Nullable<int> stop_three { get; set; }
        public Nullable<int> stop_four { get; set; }
        public Nullable<int> stop_five { get; set; }
        public Nullable<int> stop_six { get; set; }
        public Nullable<int> continue_one { get; set; }
        public Nullable<int> continue_two { get; set; }
        public Nullable<int> continue_three { get; set; }
        public Nullable<int> continue_four { get; set; }
        public Nullable<int> continue5 { get; set; }
        public Nullable<int> continue6 { get; set; }
        public Nullable<int> once_zero { get; set; }
        public Nullable<int> once_one { get; set; }
        public Nullable<int> once_two { get; set; }
        public Nullable<int> once_three { get; set; }
        public Nullable<int> once_four { get; set; }
        public Nullable<int> once_five { get; set; }
        public Nullable<int> once_six { get; set; }
        public Nullable<int> mulitple_zero { get; set; }
        public Nullable<int> mulitple_one { get; set; }
        public Nullable<int> mulitple_two { get; set; }
        public Nullable<int> mulitple_three { get; set; }
        public Nullable<int> mulitple_four { get; set; }
        public Nullable<int> mulitple_five { get; set; }
        public Nullable<int> mulitple_six { get; set; }
        public Nullable<int> oncetotal { get; set; }
        public Nullable<int> multipletotal { get; set; }
    }
}
