//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace digitallearningback.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class yzucsentities : DbContext
    {
        public yzucsentities()
            : base("name=yzucsentities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Answer_record> Answer_record { get; set; }
        public virtual DbSet<Character_image> Character_image { get; set; }
        public virtual DbSet<Cimage_mood> Cimage_mood { get; set; }
        public virtual DbSet<Cimage_profession> Cimage_profession { get; set; }
        public virtual DbSet<Concept> Concepts { get; set; }
        public virtual DbSet<Gc_mapping> Gc_mapping { get; set; }
        public virtual DbSet<InfoUser> InfoUsers { get; set; }
        public virtual DbSet<Level_group> Level_group { get; set; }
        public virtual DbSet<Q_Concept> Q_Concept { get; set; }
        public virtual DbSet<QL_Mapping> QL_Mapping { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Question_group> Question_group { get; set; }
        public virtual DbSet<Question_level> Question_level { get; set; }
        public virtual DbSet<S_Class_Question> S_Class_Question { get; set; }
        public virtual DbSet<Student_Class> Student_Class { get; set; }
        public virtual DbSet<Student_class_record> Student_class_record { get; set; }
        public virtual DbSet<User_group> User_group { get; set; }
    }
}
